resources:
  repositories:
  - repository: backend
    type: github
    endpoint: MyGitHubServiceConnection
    name: devops-project-16/backend
    trigger:
    - main

  - repository: frontend
    type: github
    endpoint: MyGitHubServiceConnection
    name: devops-project-16/frontend
    trigger: 
    - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: backend
- checkout: frontend

- script: mv $(Build.SourcesDirectory)/frontend $(Build.SourcesDirectory)/backend/
  displayName: "Move frontend folder into backend"

- script: |
    cd $(Build.SourcesDirectory)/backend
    python -m venv .venv
    .venv\Scripts\Activate.ps1
    pip install -r requirements.txt
  displayName: "Creating venv, Activating venv, Installing requirements"

- script: pytest
  displayName: "Install Running pytest unit tests"
  continueOnError: False

- script: dir $(Build.SourcesDirectory)
  displayName: 'List  current dir'
