resources:
  repositories:
  - repository: backend
    type: github
    endpoint: MyGitHubServiceConnection
    name: devops-project-16/backend
    trigger:
    - main

  - repository: frontend
    type: github
    endpoint: MyGitHubServiceConnection
    name: devops-project-16/frontend
    trigger: 
    - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: backend
- checkout: frontend

- script: mv $(Build.SourcesDirectory)/frontend $(Build.SourcesDirectory)/backend/
  displayName: "Move frontend folder into backend"

- script: |
    cd $(Build.SourcesDirectory)/backend
    python -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
  displayName: "Creating venv, Activating venv, Installing requirements"

- script: |
    cd $(Build.SourcesDirectory)/backend
    source .venv/bin/activate
    pytest
  displayName: "Running pytest for unit tests"
  continueOnError: False

- script: |
    ls $(Build.SourcesDirectory)
    ls $(Build.SourcesDirectory)/backend
  displayName: 'List  current dir'

- script: |
    cd $(Build.SourcesDirectory)/backend
    source .venv/bin/activate
    fastapi dev main.py
  displayName: "Running fastapi"